spring:
  application:
    name: ribbon-client
server:
  port: 8010
eureka:
  client:
    #enabled: true #\u5F00\u542F\u8BA4\u8BC1\uFF0C\u4E0E\u524D\u9762\u914D\u5408\u4F7F\u7528
    serviceUrl:
           defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true #\u662F\u5426\u663E\u793A\u771F\u5B9E\u7684IP\u5730\u5740