spring:
  application:
    name: ribbon-client
server:
  port: 8010
eureka:
  client:
    #enabled: true #是否开启认证
    serviceUrl:
           defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true #开启服务名显示真实的IP地址