spring:
  application:
    name: api-gateway
server:
  port: 14000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  zuul:
    ignoredServices: '*' #忽略所有未配置的service，没有进行配置的服务将不能进行访问,
                        #直接访问user-service-common也不能进行访问
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    hystrix-feign:   #自定义服务名
      path: /hystrix-feign/**
      serviceId: user-hystrix-feign  #服务serviceID
    service-common:
      path: /service-common/**
      serviceId: user-service-common