server:
  port: 8762
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
    prefer-ip-address: true
  client:
    #register-with-eureka: false #\u8868\u793A\u662F\u5426\u6CE8\u518CEureka\u670D\u52A1\u5668,\u56E0\u4E3A\u81EA\u8EAB\u4F5C\u4E3A\u670D\u52A1\u6CE8\u518C\u4E2D\u5FC3\uFF0C\u6240\u4EE5\u4E3Afalse
    #fetch-registry: false #\u662F\u5426\u4ECEeureka\u4E0A\u83B7\u53D6\u6CE8\u518C\u4FE1\u606F
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer3:8763/eureka/
