spring:
  application:
    name: turbine-hystrix
server:
  port: 12010  #服务端口
management:
  port: 12011   #管理端口
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
turbine:
  app-config: user-hystrix-feign   #监控的服务名
  cluster-name-expression: new String("default") #集群，会有很多服务，这样配置就不需要每个服务都去配置
  combine-host-port: true  #可以让同一主机上的服务通过主机名与端口号的组合来进行区分，
                             #默认情况下会以 host 来区分不同的服务，这会使得在本地调试的时候，
                             #本机上的不同服务聚合成一个服务来统计