spring:
  application:
    name: user-service-common
  datasource:
    url: jdbc:mysql://192.168.25.128:3306/shiro
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

server:
  port: 7910

eureka:
  client:
   serviceUrl:
        defaultZone: http://peer1:8761/eureka/
  instance:
    prefer-ip-address: true
    instance_id: ${spring.application.name}:${spring.application.instance_id:${server.port}}