#spring:
  #security:
    #user:
      #name: root          # 用户名
      #password: 123456    # 密码

server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #表示是否注册Eureka服务器,因为自身作为服务注册中心，所以为false
    fetch-registry: false #是否从eureka上获取注册信息
    serviceUrl:
      defaultZone: http://root:123456@localhost:8761/eureka/
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/