spring:
  application:
    name: ribbon-client-serviceconfig
server:
  port: 8011
eureka:
  client:
    #enabled: true #开启认证
    serviceUrl:
           defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
user-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule